### ISSUE TITLE
Google Maps?

### ISSUE THREAD

**Issue by FJLiJinYi** [xclud/flutter_map#1]
Do I have to use Google Maps?  Simple demo doesn't get Google map.

**Comment by xclud** [comment]
What do you mean by not getting google map? It doesn't load/show anything ?

Google Map and OSM support are built-in. However you can use any map by extending `MapProvider `class and passing it to the `MapController`. The example project has a class which extends `MapProvider`.

Please let me know if your problem has solved or you need more details.
