### ISSUE TITLE
When will flutter_map support polyline?

### ISSUE THREAD

**Issue by rty813** [xclud/flutter_map#11]
When will flutter_map support polyline?

**Comment by rty813** [comment]
And, where is the docs?

**Comment by xclud** [comment]
You can draw anything/polylines using the [CustomPaint](https://api.flutter.dev/flutter/widgets/CustomPaint-class.html) class and [MapLayoutBuilder](https://pub.dev/documentation/map/latest/map/MapLayoutBuilder-class.html). See markers example.

I will add an example (Metro Lines) but there is no eta. Meanwhile, If you face any difficulties I am here to help.

**Comment by rty813** [comment]
Thanks! I'll try it

**Comment by rty813** [comment]
![image](https://user-images.githubusercontent.com/22488813/124889398-a3a8ac80-e009-11eb-8647-47442222688d.png)
succeed! Thanks

**Comment by xclud** [comment]
I just updated the live demo to showcase polylines.

https://xclud.github.io/flutter_map/
