### ISSUE TITLE
Google maps url

### ISSUE THREAD

**Issue by 2math** [xclud/flutter_map#12]
Hi and thank you for this great plugin!

I have a hard time to figure it out how to construct the Google's url.

In your example the link looks like this
`https://www.google.com/maps/vt/pb=!1m4!1m3!1i$z!2i$x!3i$y!2m3!1e0!2sm!3i420120488!3m7!2sen!5e1105!12m4!1e68!2m2!1sset!2sRoadmap!4e0!5m1!1e0!23i4111425`

Should I use the exact same url and add `&key=My-API-KEY` behind?

Also which API should be enabled for this key "Maps JavaScript API" or another?

Thanks in advance!

**Comment by xclud** [comment]
Hi @2math,

I did more research and found out it is against Google's terms of service to use their API/tiles with 3rd party frameworks (like this package).

You have to use google's package if you need to get tile set from google. Or you have to use another tile provider. Search `free map tile servers` to find out more.

BTW, I have to update the comments in the code and provide better description.

**Comment by 2math** [comment]
Hi @xclud ,
Thank you for your response!
I have investigated too and https://www.mapbox.com/pricing/#tile looks most promising. The free quota is enough for now and if it gets expensive I can use some self hosted server and just replace the url in the app

**Comment by giaur500** [comment]
Ok, but can you tell, how exactly that url is constructed? How did you generate it? I want to get my own, for dev purpose of course. How is it obtained?

**Comment by xclud** [comment]
@giaur500 please see #5

**Comment by rajesh-h** [comment]
So does this mean we cannot use this package with google api? As far as I know google provides maps service at free of charge.

**Comment by rajesh-h** [comment]
Thank you very much @xclud for your response. I am happy to use free map services. But couldn't find any free service, My basic requirement is having a satellite view for my application. Could you please suggest any free map services?

Thank you for this wonderful package

**Comment by xclud** [comment]
OpenSteetMap is free as long as you keep the attribution/trademark text at bottom right of your map widget.

**Comment by rajesh-h** [comment]
I don't know much about maps. But when I searched what I got to know is openStreetMap doesn't have satellite view.
