### ISSUE TITLE
Is Polyline visualization and marker clustering possible?

### ISSUE THREAD

**Issue by vinnytwice** [xclud/flutter_map#13]
Hi, I'm looking into your package to replace flutter_maps as it currently doesn't support web and I do need it on my web app as well as to render custom vector maps.  I need to display polylines and to be able to make markers clusters depending on zoom level, but I can't seem to find any info about it in your API docs. Is it already possible or will be availabe any soon?
Many thanks. 
Cheers Vinny

**Comment by xclud** [comment]
Polyline visualization is possible. You can start with markers example and draw lines using CustomPaint widget. Marker clustering is on the roadmap but there's no ETA.

**Comment by vinnytwice** [comment]
Hi, thanks for answering. Markers clustering is quite important for any map and I hope you get it soon. 
Chers. 
Vinnie.

**Comment by xclud** [comment]
I just updated the live demo to include polylines.

https://xclud.github.io/flutter_map/

I am closing this issue. Please feel free to open a new issue anytime.
