### ISSUE TITLE
about the map outline

### ISSUE THREAD

**Issue by 0229liang** [xclud/flutter_map#15]
when I drag the map outline ,the map was hidden and display white background,I want to control it to disable to drag if the map outline

**Comment by xclud** [comment]
You can get the XY position of (89.999, -179.00) and (-89.999, 179.00) and check if they are out of screen bounds. Does this help you?

**Comment by 0229liang** [comment]
> You can get the XY position of (89.999, -179.00) and (-89.999, 179.00) and check if they are out of screen bounds. Does this help you?

I had solved it , thanks

**Comment by xclud** [comment]
Thank you for the feedback :)

I am closing this issue but feel free to open a new issue anytime.
