### ISSUE TITLE
Question about the flutter_map

### ISSUE THREAD

**Issue by Lawati97** [xclud/flutter_map#16]
My concern is if this package will support Huawei devices that do not support Google Services?

**Comment by xclud** [comment]
Hi @Lawati97. `Map` has no dependency on Google Services. So, Yes. It works on Huawei devices.

**Comment by Lawati97** [comment]
@xclud I would like to confirm that this plugin uses Azure or OpenStreet right?

**Comment by xclud** [comment]
This package does not use Azure or OpenStreet. **You** can decide to use any of them. You are good to go with either Azure or OpenStreet.
