### ISSUE TITLE
Does this works for Flutter WEB ?? Please add the setup for WEB 

### ISSUE THREAD

**Issue by PuneethRegonda** [xclud/flutter_map#2]

**Comment by xclud** [comment]
Hi @PuneethRegonda, the example project works on the web out of the box. no setup/configuration is needed. In example folder run `flutter run -d chrome` and it will work.

**Comment by PuneethRegonda** [comment]
Cool dude. Greate

> 
> 
> Hi @PuneethRegonda, the example project works on the web out of the box. no setup/configuration is needed. In example folder run `flutter run -d chrome` and it will work.

Cool Dude ❤... I am Loving it, I could now use map in website... This will be very helpful for my academic project. 
Thanks a lot for building such awe...  Keep going with the good stuff.
