### ISSUE TITLE
Draw polygon

### ISSUE THREAD

**Issue by ambr89** [xclud/flutter_map#22]
Is there any feature to draw polygon?

Thanks in advance.

**Comment by xclud** [comment]
It's easy. Take polyline example and modify it. Using [CustomPaint](https://api.flutter.dev/flutter/widgets/CustomPaint-class.html) is very straight forward.

If you face any difficulties let me know. I will try to help you.

**Comment by ambr89** [comment]
Thanks for the suggestion!
I try it now!
