### ISSUE TITLE
problem with LatLng

### ISSUE THREAD

**Issue by ambr89** [xclud/flutter_map#23]
I've seen that project, use LatLng object from and oldest project latlong: ^0.6.1 

If I add 
latlong: ^0.6.1  to my .jaml I receive this error

```
Because build_runner 2.1.2 depends on logging ^1.0.0 and latlong >=0.6.1 depends on logging >=0.11.3 <1.0.0, build_runner 2.1.2 is incompatible with latlong >=0.6.1.
So, because gttapp depends on both latlong ^0.6.1 and build_runner 2.1.2, version solving failed.
pub get failed (1; So, because gttapp depends on both latlong ^0.6.1 and build_runner 2.1.2, version solving failed.)
```

I've seen that there is the newest library latlong2.
There is any interest to update this project to use this new library?

**Comment by xclud** [comment]
This seems to be a dependency conflict between `latlong` and `build_runner`. There is nothing to do about `map` package. Please note my other package is [latlng](https://pub.dev/packages/latlng) not `latlong`.

In most cases using packaages with `any` version will help. e.g.:

```
dependencies:
  latlong: any
  build_runner: any
```

Also i am wondering if you add `build_runner` in `dependencies` or `devdependencies`.

**Comment by ambr89** [comment]
Yes, sorry, I've set the wrong library.
Really really sorry.
```
dependencies:
  map: ^1.0.0
  latlng: ^0.1.0
```
This worked fine.

**Comment by xclud** [comment]
You are welcome. Feel free to open a new issue any time.
