### ISSUE TITLE
More information on the https://pub.dev/packages/map page.

### ISSUE THREAD

**Issue by danteCarvalho** [xclud/flutter_map#26]
The package needs more information about some topics, like:

If you are using a google map, what is this link on the example? https://www.google.com/maps/vt/pb=!1m4!1m3!1i$z!2i$x!3i$y!2m3!1e0!2sm!3i420120488!3m7!2sen!5e1105!12m4!1e68!2m2!1sset!2sRoadmap!4e0!5m1!1e0!23i4111425  i used maps before but never saw this. where this link comes from? Can I use the api credential key? 

 is the package using the javascript api? or is it just a map with overlays?

well besides this it seems to be working well, its a great package, i tested it on linux, web, and android

**Comment by dandoii** [comment]
I'd like to know too! Have you come right? Is it possible to use your API Key somewhere?

**Comment by xclud** [comment]
Hi, thank you for the feedback. I will be happy to keep this issue open and discuss the info you and other devs need.

And about your questions:

- You can generate such urls with https://snazzymaps.com/
- There is no API key with these kind of url. I am not sure if this is a legal way of using google map api. As long as i know google's terms of use allow only the use of their own SDK and any kind of 3rd party map is illegal. So please use this url for educational purpose only.
- This package is written in Dart purely. There is nothing from google and nothing from native android/ios.

**Comment by dandoii** [comment]
I did some research and apparently you may use these URL's with no connection to the API legally. Read it somewhere on the documentation !
