### ISSUE TITLE
Unable to add markers

### ISSUE THREAD

**Issue by officialthirteen3** [xclud/flutter_map#3]
I have implemented the map but there seems no way to implement markers.

**Comment by esDotDev** [comment]
Is there any plans to update this library further? Without markers there's not much we can do with a map plugin...

**Comment by aidanm1999** [comment]
Any update on this?

**Comment by edwinmacalopu** [comment]
adding a marker would be ideal for this package

**Comment by ravijethvaaphp** [comment]
Yes please provide Add Marker functionality

**Comment by xclud** [comment]
I am happy to let you guys know markers are supported in version `0.9.0`. I appreciate your patience.
