### ISSUE TITLE
How to use satellite view?

### ISSUE THREAD

**Issue by bugrahancamlibel** [xclud/flutter_map#34]
I need to use satellite view for my application. I don't know how to generate a URI for satellite view.

**Comment by xclud** [comment]
Try this:

`'https://services.arcgisonline.com/arcgis/rest/services/World_Imagery/MapServer/tile/$z/$x/$y'`

Example here:

https://services.arcgisonline.com/arcgis/rest/services/World_Imagery/MapServer/tile/7/32/88

**Comment by bugrahancamlibel** [comment]
Thank you for your response. I tried the URL you gave but it turned out something like this:

![ground_center 10 05 2022 12_55_00](https://user-images.githubusercontent.com/58890659/167603160-d3faa89d-3116-4c42-a0ae-1910ff3fb882.png)

**Comment by xclud** [comment]
Maybe this will help?

`'https://services.arcgisonline.com/arcgis/rest/services/World_Imagery/MapServer/tile/$z/$y/$x'`

**Comment by bugrahancamlibel** [comment]
This worked perfectly! Thank you so much for your support.
