### ISSUE TITLE
Breaking changes in minor versions of the map package

### ISSUE THREAD

**Issue by MarcBritton** [xclud/flutter_map#38]
Hey,

We had a breakage in the main branch of our app due to breaking changes in a non-major version of the map package. Our pubspec specifies ^1.0.1, which according to semantic versioning, should allow us to use up to 2.0.0 of map without breaking changes, but 1.2.0 has api changes in MapTransformer that break.

This is discussed in the docs here:
https://dart.dev/tools/pub/versioning#semantic-versions

And refering to the semantic versioning spec:
https://semver.org/spec/v2.0.0-rc.1.html

the docs say:

> [the semantic versioning spec] describes the format of a version number, and the exact API behavioral differences when you increment to a later version number. Pub requires versions to be formatted that way, and to play well with the pub community, your package should follow the semantics it specifies. You should assume that the packages you depend on also follow it. (And if you find out they don’t, let their authors know!)

As we depended on ^1.0.1 in our pubspec file, I believe we should be able to upgrade to any version of map in that range and not receive breaking changes.

Thanks for your work on the map package which we're using in our project and is great.

**Comment by xclud** [comment]
Hi,

You are right. I am trying to prepare for v2 but before that I needed some fixes. Sorry for the breakage. You may use v1.1.0 but migrating to v1.2.0 is quite easy.

And thank you for the links.
