### ISSUE TITLE
Hello Sir!  how can we generate url key for this map

### ISSUE THREAD

**Issue by Umer8627** [xclud/flutter_map#39]

**Comment by xclud** [comment]
Do you mean google's API Key? If yes, as long as I know you are not allowed to use google's api key with 3rd party packages.

**Comment by Umer8627** [comment]
Sir how can we add our api key


![legal notice](https://user-images.githubusercontent.com/49708591/176635181-56226844-9d05-44bd-a398-71df60b85ebe.JPG)

**Comment by xclud** [comment]
This is not a key. This is the style/coloring google uses for rendering. See #12.

**Comment by xclud** [comment]
#5

**Comment by Umer8627** [comment]
When I zoom out  in map then i am facing this error 

Object event

![WhatsApp Image 2022-06-30 at 1 55 29 PM](https://user-images.githubusercontent.com/49708591/176636350-76b3a2e9-d42a-4fca-9b26-c7ff4b357897.jpeg)

**Comment by xclud** [comment]
Update to a newer version of map.

There are some breaking changes in version 1.2 so if your project is in the early days of development I recommend you to upgrading to version 1.2. If it's a pain, version 1.1.0 will do.

**Comment by Umer8627** [comment]
Sir ! I am facing same issue. I am using package map 1.1.0 But still facing error
Here is my error
![WhatsApp Image 2022-06-30 at 6 34 44 PM](https://user-images.githubusercontent.com/49708591/176691184-42ddb0c7-e96c-451a-bc80-1c02ee69c5ee.jpeg)

**Comment by Umer8627** [comment]
And When i full zoom out then my whole project was stop working.

![WhatsApp Image 2022-06-30 at 6 43 28 PM](https://user-images.githubusercontent.com/49708591/176693028-d8593486-8ac9-4a94-afbe-05a8d3892ed3.jpeg)

**Comment by xclud** [comment]
You have to limit controller.zoom between [0, 18] range.

```
if(controller.zoom < 0)
{
  controller.zoom = 0;
}

if(controller.zoom > 18)
{
  controller.zoom = 18;
}
```
