### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by welitonsousa** [xclud/flutter_map#43]
How enable dark theme?

**Comment by xclud** [comment]
See the example project "Raster Tiles".

**Comment by xclud** [comment]
This package does not have any color scheme by itself. Everything depends on the tile provider you are using.

I am closing this issue but please feel free to open a new one.

**Comment by xclud** [comment]
This package does not have any color scheme by itself. Everything depends on the tile provider you are using.

I am closing this issue but please feel free to open a new one.
