### ISSUE TITLE
intl bug w/ repro steps

### ISSUE THREAD

**Issue by noga-dev** [xclud/flutter_map#53]
Hi, first of all nice package. I've been playing around with it for a few days and other than this bug (and another one where the current view jumps to random location after panning/scaling) it's incredible. Anyway here's a bug with steps to repro for your convenience.

Using the included example:
1. Add this dependency to pubspec:
```
flutter_localizations:
    sdk: flutter
```
2. Import in main.dart:
```
import 'package:flutter_localizations/flutter_localizations.dart';
```
3. Modify main.dart to this:
```
class MapApp extends StatelessWidget {
  const MapApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      supportedLocales: [Locale('he')],
      localizationsDelegates: [
        GlobalWidgetsLocalizations.delegate,
        GlobalMaterialLocalizations.delegate,
      ],
      home: HomePage(),
    );
  }
}
```
4. Go to Shapes or Metro screens and zoom in or out to observe this behavior:
![Map_2p7TLapgyC](https://user-images.githubusercontent.com/2067558/212487945-3d42aacf-b144-4be4-b7fa-f71cf9327bc7.gif)

Only tried this on Win and web, haven't tried other platforms but I assume it's universal.

**Comment by xclud** [comment]
I tested the demo app with localization and it works. I am not able to reproduce the bug.

What version of flutter are you using?

**Comment by noga-dev** [comment]
Latest stable

**Comment by noga-dev** [comment]
I believe it's related to RTL languages.

**Comment by noga-dev** [comment]
Seems like wrapping home in ```Directionality``` and setting ```textDirection``` to RTL also causes this.

**Comment by noga-dev** [comment]
Looks like the workaround fix is wrapping ```MapLayout``` in ```Directionality``` and setting ```textDirection: TextDirection.ltr```.

**Comment by xclud** [comment]
Yes. It has to be ltr.

**Comment by noga-dev** [comment]
Sounds like it should be explicitly added in the example. I'd also remove the custom _clamp function and just use double's built in one.

**Comment by xclud** [comment]
Bests.
