### ISSUE TITLE
how to get location when we tap on map?

### ISSUE THREAD

**Issue by mitesh77** [xclud/flutter_map#6]
I don't have any way to find the location when we click in the map and get loction

**Comment by xclud** [comment]
There is [currently] no way to get the location of the clicked point. But you can get the location for the center from `_controller.center`.

**Comment by mitesh77** [comment]
I know but need a touch or tap location.

**Comment by xclud** [comment]
I put this feature request on the list. I hope you can wait a while. Meanwhile, please feel free to contribute to the project.

**Comment by xclud** [comment]
This is implemented in version `0.4.0` of the package. Please update your dependencies.
